
###
GET {{baseUrl}}

###
POST {{baseUrl}}
Content-Type: application/json

{
    "content": "Buy sour Milk when programmming",
    "important": false
}

###
GET {{baseUrl}}

###
DELETE {{baseUrl}}/68dd4e77856b96e9fc4f1823
