###
GET {{baseURL}}

###
GET {{baseURL}}/68dd5c5970d79ac9ddf2715c

###
DELETE {{baseURL}}/3

###
POST {{baseURL}}
Content-Type: application/json

{
  "name": "Testi Testinen",
  "number": "0500500"
}

###
DELETE {{baseURL}}/68e2b858c9bfe9bd0b173dbe

###
PUT {{baseURL}}/68dd5c5970d79ac9ddf2715c
Content-Type: application/json

{
  "name": "Jyri Huhtala",
  "number": "0400123123"
}

