###
GET {{baseURL}}

###
DELETE {{baseURL}}/3

###
POST {{baseURL}}
Content-Type: application/json

{
  "name": "Testi Testinen",
  "number": "0500500"
}

###
DELETE {{baseURL}}/68e2b858c9bfe9bd0b173dbe

